name = "Libtiff_jll"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.3.0+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
LERC_jll = "88015f11-f218-50d7-93a8-a6af411a945d"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Zstd_jll = "3161d3a3-bdf6-5164-811a-617609db77b4"

[compat]
JLLWrappers = "1.2.0"
julia = "1.6"
