name = "Xorg_libxcb_jll"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+3"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
XSLT_jll = "aed1982a-8fda-507f-9586-7b0439959a61"
Xorg_libXau_jll = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Xorg_libpthread_stubs_jll = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Xorg_libXdmcp_jll = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"

[compat]
JLLWrappers = "1.1.0"
julia = "1.0"
